- hosts: web
  become: yes
  tasks:
    - name: Install nginx (Amazon Linux)
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy application page
      copy:
        src: ../app/index.html
        dest: /usr/share/nginx/html/index.html